#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Jan 07, 2019 11:31:56 AM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import konfirmasi_support
import time
import sqlite3
from tkinter import messagebox

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    konfirmasi_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    konfirmasi_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font11 = "-family Verdana -size 12 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"
        font12 = "-family {UD Digi Kyokasho NK-B} -size 11 -weight "  \
            "bold -slant roman -underline 0 -overstrike 0"
        font9 = "-family {Sitka Small} -size 12 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("600x425+650+150")
        top.title("Pengantaran")
        top.configure(background="#cbd856")

        self.Canvas1 = tk.Canvas(top)
        self.Canvas1.place(relx=0.15, rely=0.188, relheight=0.713
                , relwidth=0.688)
        self.Canvas1.configure(background="#97c157")
        self.Canvas1.configure(closeenough="0.0")
        self.Canvas1.configure(highlightthickness="0")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief='ridge')
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")
        self.Canvas1.configure(width=413)

        name = tk.StringVar()
        no = tk.StringVar()
        address = tk.StringVar()

        def insert_data():
            nem = name.get()
            hp = no.get()
            adres = address.get()
            konek=sqlite3.connect("laundry.db")
            with konek :
                data = konek.cursor()
                data.execute("INSERT INTO delivery (nama,no_hp,alamat)"
                             "VALUES (?,?,?)",(nem,hp,adres,))
                konek.commit()

        self.Label1 = tk.Label(self.Canvas1)
        self.Label1.place(relx=0.266, rely=0.033, height=31, width=201)
        self.Label1.configure(background="#97c157")
        self.Label1.configure(borderwidth="0")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Form Pengantaran''')

        self.Label1_2 = tk.Label(self.Canvas1)
        self.Label1_2.place(relx=0.073, rely=0.231, height=31, width=141)
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(anchor='w')
        self.Label1_2.configure(background="#97c157")
        self.Label1_2.configure(borderwidth="0")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(font=font9)
        self.Label1_2.configure(foreground="#000000")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="black")
        self.Label1_2.configure(text='''Nama''')
        self.Label1_2.configure(width=141)

        self.Label1_3 = tk.Label(self.Canvas1)
        self.Label1_3.place(relx=0.073, rely=0.429, height=31, width=141)
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(activeforeground="black")
        self.Label1_3.configure(anchor='w')
        self.Label1_3.configure(background="#97c157")
        self.Label1_3.configure(borderwidth="0")
        self.Label1_3.configure(disabledforeground="#a3a3a3")
        self.Label1_3.configure(font=font9)
        self.Label1_3.configure(foreground="#000000")
        self.Label1_3.configure(highlightbackground="#d9d9d9")
        self.Label1_3.configure(highlightcolor="black")
        self.Label1_3.configure(text='''No HP''')
        self.Label1_3.configure(width=141)

        self.Label1_4 = tk.Label(self.Canvas1)
        self.Label1_4.place(relx=0.073, rely=0.627, height=31, width=141)
        self.Label1_4.configure(activebackground="#f9f9f9")
        self.Label1_4.configure(activeforeground="black")
        self.Label1_4.configure(anchor='w')
        self.Label1_4.configure(background="#97c157")
        self.Label1_4.configure(borderwidth="0")
        self.Label1_4.configure(disabledforeground="#a3a3a3")
        self.Label1_4.configure(font=font9)
        self.Label1_4.configure(foreground="#000000")
        self.Label1_4.configure(highlightbackground="#d9d9d9")
        self.Label1_4.configure(highlightcolor="black")
        self.Label1_4.configure(text='''Alamat''')
        self.Label1_4.configure(width=141)

        def deliv():
            insert_data()
            messagebox.showinfo("OK!!","Laundry Anda Akan Diproses dalam 3 - 4 Hari")
            quit()

        self.Button1 = tk.Button(self.Canvas1)
        self.Button1.place(relx=0.726, rely=0.825, height=33, width=86)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d8915b")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font12)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''OK''',command=deliv)
        self.Button1.configure(width=86)

        self.Entry1 = tk.Entry(self.Canvas1)
        self.Entry1.place(relx=0.387, rely=0.231,height=34, relwidth=0.494)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(width=204)
        self.Entry1.configure(textvar=name)

        self.Entry1_5 = tk.Entry(self.Canvas1)
        self.Entry1_5.place(relx=0.387, rely=0.429,height=34, relwidth=0.494)
        self.Entry1_5.configure(background="white")
        self.Entry1_5.configure(disabledforeground="#a3a3a3")
        self.Entry1_5.configure(font="TkFixedFont")
        self.Entry1_5.configure(foreground="#000000")
        self.Entry1_5.configure(highlightbackground="#d9d9d9")
        self.Entry1_5.configure(highlightcolor="black")
        self.Entry1_5.configure(insertbackground="black")
        self.Entry1_5.configure(selectbackground="#c4c4c4")
        self.Entry1_5.configure(selectforeground="black")
        self.Entry1_5.configure(textvar=no)

        self.Entry1_6 = tk.Entry(self.Canvas1)
        self.Entry1_6.place(relx=0.387, rely=0.627,height=34, relwidth=0.494)
        self.Entry1_6.configure(background="white")
        self.Entry1_6.configure(disabledforeground="#a3a3a3")
        self.Entry1_6.configure(font="TkFixedFont")
        self.Entry1_6.configure(foreground="#000000")
        self.Entry1_6.configure(highlightbackground="#d9d9d9")
        self.Entry1_6.configure(highlightcolor="black")
        self.Entry1_6.configure(insertbackground="black")
        self.Entry1_6.configure(selectbackground="#c4c4c4")
        self.Entry1_6.configure(selectforeground="black")
        self.Entry1_6.configure(textvar=address)

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.617, rely=0.047, height=37, width=222)
        self.Label2.configure(anchor='e')
        self.Label2.configure(background="#cbd856")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font12)
        self.Label2.configure(foreground="#000000")
        waktu = time.asctime(time.localtime(time.time()))
        self.Label2.configure(text=waktu)
        self.Label2.configure(width=222)

        self.Label2_1 = tk.Label(top)
        self.Label2_1.place(relx=0.017, rely=0.047, height=37, width=292)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#cbd856")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font=font11)
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''Mohon Isi Form Berikut''')
        self.Label2_1.configure(width=292)

if __name__ == '__main__':
    vp_start_gui()





