#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Dec 15, 2018 12:51:18 AM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import log_in_support
import sqlite3
import time
from tkinter import messagebox


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    log_in_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    log_in_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font9 = "-family Arial -size 11 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"

        top.geometry("600x450+650+150")
        top.title("Login")
        top.configure(background="#9e00d8")
        waktu = time.asctime(time.localtime(time.time()))
        jam = tk.Label(root,text=waktu,bg='#9e00d8',font="Verdana 10")
        jam.place(x=200,y=10)
        self.Canvas1 = tk.Canvas(top)
        self.Canvas1.place(relx=0.183, rely=0.089, relheight=0.807
                , relwidth=0.655)
        self.Canvas1.configure(background="#bc4ed8")
        self.Canvas1.configure(highlightbackground="#bc4ed8")
        self.Canvas1.configure(highlightcolor="#bc4ed8")
        self.Canvas1.configure(insertbackground="#bc4ed8")
        self.Canvas1.configure(relief='ridge')
        self.Canvas1.configure(selectbackground="#bc4ed8")
        self.Canvas1.configure(selectforeground="#ff36d0")
        self.Canvas1.configure(width=393)

        usr=tk.StringVar()
        pwd=tk.StringVar()

        self.Entry1 = tk.Entry(self.Canvas1)
        self.Entry1.place(relx=0.127, rely=0.551,height=34, relwidth=0.646)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(width=254)
        self.Entry1.configure(textvariable=usr)

        self.Entry1_1 = tk.Entry(self.Canvas1)
        self.Entry1_1.place(relx=0.127, rely=0.744,height=34, relwidth=0.646)
        self.Entry1_1.configure(background="white")
        self.Entry1_1.configure(disabledforeground="#a3a3a3")
        self.Entry1_1.configure(font="TkFixedFont")
        self.Entry1_1.configure(foreground="#000000")
        self.Entry1_1.configure(highlightbackground="#d9d9d9")
        self.Entry1_1.configure(highlightcolor="black")
        self.Entry1_1.configure(insertbackground="black")
        self.Entry1_1.configure(selectbackground="#c4c4c4")
        self.Entry1_1.configure(selectforeground="black")
        self.Entry1_1.configure(width=254)
        self.Entry1_1.configure(textvariable=pwd,show="*")

        self.Label2 = tk.Label(self.Canvas1)
        self.Label2.place(relx=0.127, rely=0.468, height=27, width=81)
        self.Label2.configure(activebackground="#bc4ed8")
        self.Label2.configure(activeforeground="white")
        self.Label2.configure(activeforeground="#bc4ed8")
        self.Label2.configure(background="#bc4ed8")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font9)
        self.Label2.configure(foreground="#ffffff")
        self.Label2.configure(text='''ID CARD''')

        self.Label2_2 = tk.Label(self.Canvas1)
        self.Label2_2.place(relx=0.127, rely=0.661, height=26, width=114)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#bc4ed8")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font=font9)
        self.Label2_2.configure(foreground="#ffffff")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''PASSWORD''')
        self.Label2_2.configure(width=114)
        with sqlite3.connect("laundry.db") as db :
            data = db.cursor()
        def move3a():
            if usr.get() == "" or pwd.get() == "":
                messagebox.showerror("NO","Data Tidak Boleh Kosong")
            else:
                data.execute("SELECT * FROM member WHERE nama_pelanggan = ? AND pass_word = ?", (usr.get(), pwd.get()))
                if data.fetchone():
                    messagebox.showinfo("OK","Login Berhasil")
                    root.destroy()
                    from orderan import vp_start_gui
                    vp_start_gui()
                else:
                    messagebox.showwarning("WARNING","Username/Password Salah")
        self.Button1 = tk.Button(self.Canvas1)
        self.Button1.place(relx=0.025, rely=0.882, height=33, width=376)
        self.Button1.configure(activebackground="#ebff36")
        self.Button1.configure(activeforeground="#ebff36")
        self.Button1.configure(background="#ebff36")
        self.Button1.configure(disabledforeground="#ebff36")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''LOGIN''',command=move3a)
        self.Button1.configure(width=376)

        self.Label3 = tk.Label(self.Canvas1)
        self.Label3.place(relx=0.0, rely=0.0, height=26, width=392)
        self.Label3.configure(background="#ebff36")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Member Login''')
        self.Label3.configure(width=392)

        self.Canvas2 = tk.Canvas(self.Canvas1)
        self.Canvas2.place(relx=0.331, rely=0.125, relheight=0.300
                , relwidth=0.350)
        self.img = tk.PhotoImage(file="login_update_lagi.png")
        self.Canvas2.create_image(77,77,anchor='center', image=self.img)
        self.Canvas2.image = self.img
        self.Canvas2.configure(background="#d9d9d9")
        self.Canvas2.configure(borderwidth="0")
        self.Canvas2.configure(insertbackground="black")
        self.Canvas2.configure(relief='ridge')
        self.Canvas2.configure(selectbackground="#c4c4c4")
        self.Canvas2.configure(selectforeground="black")
        self.Canvas2.configure(takefocus="0")

if __name__ == '__main__':
    vp_start_gui()





