#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Jan 06, 2019 09:31:12 PM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import orderan_support
import home_page
import time
import sqlite3
from tkinter import messagebox

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    orderan_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    orderan_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font10 = "-family Arial -size 12 -weight normal -slant roman "  \
            "-underline 0 -overstrike 0"
        font11 = "-family Arial -size 11 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"
        font9 = "-family Arial -size 15 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"

        top.geometry("600x457+819+318")
        top.title("Proses")
        top.configure(background="#4747d8")

        self.Canvas1 = tk.Canvas(top)
        self.Canvas1.place(relx=0.017, rely=0.022, relheight=0.357
                , relwidth=0.972)
        self.Canvas1.configure(background="yellow")
        self.Canvas1.configure(closeenough="0.0")
        self.Canvas1.configure(highlightbackground="#2d26ef")
        self.Canvas1.configure(highlightthickness="0")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief='ridge')
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")
        self.Canvas1.configure(width=583)

        self.Label1 = tk.Label(self.Canvas1)
        self.Label1.place(relx=0.0, rely=0.0, height=36, width=402)
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(justify='left')
        self.Label1.configure(text='''Input Barang''')
        self.Label1.configure(width=402)

        self.Label1_1 = tk.Label(self.Canvas1)
        self.Label1_1.place(relx=0.690, rely=0.0, height=36, width=182)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#ffffff")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font=font11)
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        waktu = time.asctime(time.localtime(time.time()))
        self.Label1_1.configure(text=waktu)

        a = tk.IntVar()
        b = tk.IntVar()
        c = tk.IntVar()
        d = tk.IntVar()
        e = tk.IntVar()
        f = tk.IntVar()
        g = tk.StringVar()
        g.set("0")
        h = tk.StringVar()
        h.set("0")
        i = tk.StringVar()
        i.set("0")
        j = tk.StringVar()
        j.set("0")
        k = tk.StringVar()
        k.set("0")
        l = tk.StringVar()
        l.set("0")
        m = tk.StringVar()
        n = tk.StringVar()
        o = tk.StringVar()
        p = tk.StringVar()

        def pricelist():
            gg = int(g.get())
            hh = int(h.get())
            ii = int(i.get())
            jj = int(j.get())
            kk = int(k.get())
            ll = int(l.get())
            harga = gg+hh+ii+jj+kk+ll
            jadi = harga*1000
            jadiharga = "Rp",str("%i" % jadi)
            m.set(jadiharga)
            if home_page.v.get()==0:
                n.set("10%")
            else :
                n.set('0%')
        def total() :
            gg = int(g.get())
            hh = int(h.get())
            ii = int(i.get())
            jj = int(j.get())
            kk = int(k.get())
            ll = int(l.get())
            harga = gg+hh+ii+jj+kk+ll
            jadi = harga*1000
            oo = int(o.get())
            dis = 0.1*jadi
            disc = jadi-dis
            if home_page.v.get()==0:
                totalsemua = oo-disc
                if totalsemua < 0 :
                    messagebox.showwarning("Perhatian","Uang Tidak Boleh Kurang")
                    o.set("")
                    p.set("")
                else :
                    semua = "Rp",str("%i" % totalsemua)
                    p.set(semua)
            else :
                totalsemua = oo-jadi
                if totalsemua < 0 :
                    messagebox.showwarning("Perhatian","Uang Tidak Boleh Kurang")
                    o.set("")
                else :
                    p.set("")
                    semua = "Rp",str("%i" % totalsemua)
                    p.set(semua)
        def inputan():
            g1 = g.get()
            h1 = h.get()
            i1 = i.get()
            j1 = j.get()
            k1 = k.get()
            l1 = l.get()
            konek=sqlite3.connect("laundry.db")
            data = konek.cursor()
            if home_page.v.get()==0:
                data.execute("CREATE TABLE IF NOT EXISTS barang (jumlah_baju text,"
                             "jumlah_rok text,jumlah_jilbab text,jumlah_celana text,"
                             "jumlah_kaos text,jumlah_lain text)")
                data.execute("INSERT INTO barang (jumlah_baju,jumlah_rok,jumlah_jilbab,"
                             "jumlah_celana,jumlah_kaos,jumlah_lain)"
                             "VALUES (?,?,?,?,?,?)",(g1,h1,i1,j1,k1,l1,))
            else :
                data.execute("CREATE TABLE IF NOT EXISTS pesanan (jumlah_baju text,"
                             "jumlah_rok text,jumlah_jilbab text,jumlah_celana text,"
                             "jumlah_kaos text,jumlah_lain text)")
                data.execute("INSERT INTO pesanan (jumlah_baju,jumlah_rok,jumlah_jilbab,"
                             "jumlah_celana,jumlah_kaos,jumlah_lain)"
                             "VALUES (?,?,?,?,?,?)",(g1,h1,i1,j1,k1,l1,))
            konek.commit()
        def ulangi():
            a.set(0)
            b.set(0)
            c.set(0)
            d.set(0)
            e.set(0)
            f.set(0)
            self.Entry1.configure(state='disabled')
            g.set("0")
            self.Entry1_9.configure(state='disabled')
            h.set("0")
            self.Entry1_4.configure(state='disabled')
            i.set("0")
            self.Entry1_10.configure(state='disabled')
            j.set("0")
            self.Entry1_5.configure(state='disabled')
            k.set("0")
            self.Entry1_11.configure(state='disabled')
            l.set("0")
            m.set("")
            n.set("")
            o.set("")
            p.set("")
        def antar():
            inputan()
            if home_page.v.get()==0:
                messagebox.showinfo("OK!!","Laundry Anda Akan Diproses dalam 2 - 3 Hari")
                quit()
            else :
                root.destroy()
                from konfirmasi import vp_start_gui
                vp_start_gui()
        def baju():
            if a.get()==1 :
                self.Entry1.configure(state='normal')
                self.Entry1.delete('0')
                g.set("")
            else :
                self.Entry1.configure(state='disabled')
                g.set('0')
        def celana():
            if d.get()==1 :
                self.Entry1_9.configure(state='normal')
                self.Entry1_9.delete('0')
                j.set("")
            else :
                self.Entry1_9.configure(state='disabled')
                j.set('0')
        def rok():
            if b.get()==1 :
                self.Entry1_4.configure(state='normal')
                self.Entry1_4.delete('0')
                h.set("")
            else :
                self.Entry1_4.configure(state='disabled')
                h.set('0')
        def kaos():
            if e.get()==1 :
                self.Entry1_10.configure(state='normal')
                self.Entry1_10.delete('0')
                k.set("")
            else :
                self.Entry1_10.configure(state='disabled')
                k.set('0')
        def jilbab():
            if c.get()==1 :
                self.Entry1_5.configure(state='normal')
                self.Entry1_5.delete('0')
                i.set("")
            else :
                self.Entry1_5.configure(state='disabled')
                i.set('0')
        def lain():
            if f.get()==1 :
                self.Entry1_11.configure(state='normal')
                self.Entry1_11.delete('0')
                l.set("")
            else :
                self.Entry1_11.configure(state='disabled')
                l.set('0')
        self.Checkbutton1 = tk.Checkbutton(self.Canvas1)
        self.Checkbutton1.place(relx=0.017, rely=0.276, relheight=0.215
                , relwidth=0.136)
        self.Checkbutton1.configure(activebackground="#ececec")
        self.Checkbutton1.configure(activeforeground="#000000")
        self.Checkbutton1.configure(background="yellow")
        self.Checkbutton1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1.configure(font=font10)
        self.Checkbutton1.configure(foreground="black")
        self.Checkbutton1.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1.configure(highlightcolor="black")
        self.Checkbutton1.configure(justify='left')
        self.Checkbutton1.configure(text='''Baju''',variable=a,onvalue=1,offvalue=0,command=baju)
        self.Checkbutton1.configure(width=79)

        self.Checkbutton1_2 = tk.Checkbutton(self.Canvas1)
        self.Checkbutton1_2.place(relx=0.015, rely=0.491, relheight=0.215
                , relwidth=0.136)
        self.Checkbutton1_2.configure(activebackground="#ececec")
        self.Checkbutton1_2.configure(activeforeground="#000000")
        self.Checkbutton1_2.configure(background="yellow")
        self.Checkbutton1_2.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1_2.configure(font=font10)
        self.Checkbutton1_2.configure(foreground="black")
        self.Checkbutton1_2.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1_2.configure(highlightcolor="black")
        self.Checkbutton1_2.configure(justify='left')
        self.Checkbutton1_2.configure(text='''Rok''',variable=b,onvalue=1,offvalue=0,command=rok)

        self.Checkbutton1_3 = tk.Checkbutton(self.Canvas1)
        self.Checkbutton1_3.place(relx=0.026, rely=0.705, relheight=0.215
                , relwidth=0.136)
        self.Checkbutton1_3.configure(activebackground="#ececec")
        self.Checkbutton1_3.configure(activeforeground="#000000")
        self.Checkbutton1_3.configure(background='yellow')
        self.Checkbutton1_3.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1_3.configure(font=font10)
        self.Checkbutton1_3.configure(foreground="black")
        self.Checkbutton1_3.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1_3.configure(highlightcolor="black")
        self.Checkbutton1_3.configure(justify='left')
        self.Checkbutton1_3.configure(text='''Jilbab''',variable=c,onvalue=1,offvalue=0,command=jilbab)

        self.Entry1 = tk.Entry(self.Canvas1)
        self.Entry1.place(relx=0.223, rely=0.307,height=24, relwidth=0.178)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(width=104)
        self.Entry1.configure(state='disabled')
        self.Entry1.configure(textvariable=g)


        self.Entry1_4 = tk.Entry(self.Canvas1)
        self.Entry1_4.place(relx=0.223, rely=0.521,height=24, relwidth=0.178)
        self.Entry1_4.configure(background="white")
        self.Entry1_4.configure(disabledforeground="#a3a3a3")
        self.Entry1_4.configure(font="TkFixedFont")
        self.Entry1_4.configure(foreground="#000000")
        self.Entry1_4.configure(highlightbackground="#d9d9d9")
        self.Entry1_4.configure(highlightcolor="black")
        self.Entry1_4.configure(insertbackground="black")
        self.Entry1_4.configure(selectbackground="#c4c4c4")
        self.Entry1_4.configure(selectforeground="black")
        self.Entry1_4.configure(width=104)
        self.Entry1_4.configure(state='disabled')
        self.Entry1_4.configure(textvariable=h)

        self.Entry1_5 = tk.Entry(self.Canvas1)
        self.Entry1_5.place(relx=0.223, rely=0.736,height=24, relwidth=0.178)
        self.Entry1_5.configure(background="white")
        self.Entry1_5.configure(disabledforeground="#a3a3a3")
        self.Entry1_5.configure(font="TkFixedFont")
        self.Entry1_5.configure(foreground="#000000")
        self.Entry1_5.configure(highlightbackground="#d9d9d9")
        self.Entry1_5.configure(highlightcolor="black")
        self.Entry1_5.configure(insertbackground="black")
        self.Entry1_5.configure(selectbackground="#c4c4c4")
        self.Entry1_5.configure(selectforeground="black")
        self.Entry1_5.configure(width=104)
        self.Entry1_5.configure(state='disabled')
        self.Entry1_5.configure(textvariable=i)


        self.Checkbutton1_6 = tk.Checkbutton(self.Canvas1)
        self.Checkbutton1_6.place(relx=0.475, rely=0.276, relheight=0.215
                , relwidth=0.136)
        self.Checkbutton1_6.configure(activebackground="#ececec")
        self.Checkbutton1_6.configure(activeforeground="#000000")
        self.Checkbutton1_6.configure(background="yellow")
        self.Checkbutton1_6.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1_6.configure(font=font10)
        self.Checkbutton1_6.configure(foreground="black")
        self.Checkbutton1_6.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1_6.configure(highlightcolor="black")
        self.Checkbutton1_6.configure(justify='left')
        self.Checkbutton1_6.configure(text='''Celana''',variable=d,onvalue=1,offvalue=0,command=celana)

        self.Checkbutton1_7 = tk.Checkbutton(self.Canvas1)
        self.Checkbutton1_7.place(relx=0.463, rely=0.491, relheight=0.215
                , relwidth=0.136)
        self.Checkbutton1_7.configure(activebackground="#ececec")
        self.Checkbutton1_7.configure(activeforeground="#000000")
        self.Checkbutton1_7.configure(background="yellow")
        self.Checkbutton1_7.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1_7.configure(font=font10)
        self.Checkbutton1_7.configure(foreground="black")
        self.Checkbutton1_7.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1_7.configure(highlightcolor="black")
        self.Checkbutton1_7.configure(justify='left')
        self.Checkbutton1_7.configure(text='''Kaos''',variable=e,onvalue=1,offvalue=0,command=kaos)

        self.Checkbutton1_8 = tk.Checkbutton(self.Canvas1)
        self.Checkbutton1_8.place(relx=0.473, rely=0.715, relheight=0.215
                , relwidth=0.221)
        self.Checkbutton1_8.configure(activebackground="#ececec")
        self.Checkbutton1_8.configure(activeforeground="#000000")
        self.Checkbutton1_8.configure(anchor='nw')
        self.Checkbutton1_8.configure(background="yellow")
        self.Checkbutton1_8.configure(compound="left")
        self.Checkbutton1_8.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1_8.configure(font=font10)
        self.Checkbutton1_8.configure(foreground="black")
        self.Checkbutton1_8.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1_8.configure(highlightcolor="black")
        self.Checkbutton1_8.configure(justify='left')
        self.Checkbutton1_8.configure(text='''Lain - Lain''',variable=f,onvalue=1,offvalue=0,command=lain)
        self.Checkbutton1_8.configure(width=129)

        self.Entry1_9 = tk.Entry(self.Canvas1)
        self.Entry1_9.place(relx=0.72, rely=0.307,height=24, relwidth=0.196)
        self.Entry1_9.configure(background="white")
        self.Entry1_9.configure(disabledforeground="#a3a3a3")
        self.Entry1_9.configure(font="TkFixedFont")
        self.Entry1_9.configure(foreground="#000000")
        self.Entry1_9.configure(highlightbackground="#d9d9d9")
        self.Entry1_9.configure(highlightcolor="black")
        self.Entry1_9.configure(insertbackground="black")
        self.Entry1_9.configure(selectbackground="#c4c4c4")
        self.Entry1_9.configure(selectforeground="black")
        self.Entry1_9.configure(width=114)
        self.Entry1_9.configure(state='disabled')
        self.Entry1_9.configure(textvariable=j)

        self.Entry1_10 = tk.Entry(self.Canvas1)
        self.Entry1_10.place(relx=0.72, rely=0.521,height=24, relwidth=0.196)
        self.Entry1_10.configure(background="white")
        self.Entry1_10.configure(disabledforeground="#a3a3a3")
        self.Entry1_10.configure(font="TkFixedFont")
        self.Entry1_10.configure(foreground="#000000")
        self.Entry1_10.configure(highlightbackground="#d9d9d9")
        self.Entry1_10.configure(highlightcolor="black")
        self.Entry1_10.configure(insertbackground="black")
        self.Entry1_10.configure(selectbackground="#c4c4c4")
        self.Entry1_10.configure(selectforeground="black")
        self.Entry1_10.configure(width=114)
        self.Entry1_10.configure(state='disabled')
        self.Entry1_10.configure(textvariable=k)

        self.Entry1_11 = tk.Entry(self.Canvas1)
        self.Entry1_11.place(relx=0.720, rely=0.736,height=24, relwidth=0.196)
        self.Entry1_11.configure(background="white")
        self.Entry1_11.configure(disabledforeground="#a3a3a3")
        self.Entry1_11.configure(font="TkFixedFont")
        self.Entry1_11.configure(foreground="#000000")
        self.Entry1_11.configure(highlightbackground="#d9d9d9")
        self.Entry1_11.configure(highlightcolor="black")
        self.Entry1_11.configure(insertbackground="black")
        self.Entry1_11.configure(selectbackground="#c4c4c4")
        self.Entry1_11.configure(selectforeground="black")
        self.Entry1_11.configure(width=114)
        self.Entry1_11.configure(state='disabled')
        self.Entry1_11.configure(textvariable=l)

        self.Canvas2 = tk.Canvas(top)
        self.Canvas2.place(relx=0.017, rely=0.525, relheight=0.335
                , relwidth=0.972)
        self.Canvas2.configure(background="yellow")
        self.Canvas2.configure(closeenough="0.0")
        self.Canvas2.configure(highlightbackground="#4747d8")
        self.Canvas2.configure(highlightthickness="0")
        self.Canvas2.configure(insertbackground="black")
        self.Canvas2.configure(relief='ridge')
        self.Canvas2.configure(selectbackground="#c4c4c4")
        self.Canvas2.configure(selectforeground="black")
        self.Canvas2.configure(width=583)

        self.Label2 = tk.Label(self.Canvas2)
        self.Label2.place(relx=0.034, rely=0.392, height=27, width=114)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="yellow")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font11)
        self.Label2.configure(foreground="black")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Total Harga''')

        self.Label2_12 = tk.Label(self.Canvas2)
        self.Label2_12.place(relx=0.030, rely=0.719, height=27, width=154)
        self.Label2_12.configure(activebackground="#f9f9f9")
        self.Label2_12.configure(activeforeground="black")
        self.Label2_12.configure(background="yellow")
        self.Label2_12.configure(disabledforeground="#a3a3a3")
        self.Label2_12.configure(font=font11)
        self.Label2_12.configure(foreground="black")
        self.Label2_12.configure(highlightbackground="#d9d9d9")
        self.Label2_12.configure(highlightcolor="black")
        self.Label2_12.configure(text='''Diskon Member''')

        self.Entry1_6 = tk.Entry(self.Canvas2)
        self.Entry1_6.place(relx=0.309, rely=0.392,height=24, relwidth=0.178)
        self.Entry1_6.configure(background="white")
        self.Entry1_6.configure(disabledforeground="#a3a3a3")
        self.Entry1_6.configure(font="TkFixedFont")
        self.Entry1_6.configure(foreground="#000000")
        self.Entry1_6.configure(highlightbackground="#d9d9d9")
        self.Entry1_6.configure(highlightcolor="black")
        self.Entry1_6.configure(insertbackground="black")
        self.Entry1_6.configure(selectbackground="#c4c4c4")
        self.Entry1_6.configure(selectforeground="black")
        self.Entry1_6.configure(textvariable=m)
        self.Entry1_6.configure(state='disabled')

        self.Entry1_2 = tk.Entry(self.Canvas2)
        self.Entry1_2.place(relx=0.309, rely=0.719,height=24, relwidth=0.178)
        self.Entry1_2.configure(background="white")
        self.Entry1_2.configure(disabledforeground="#a3a3a3")
        self.Entry1_2.configure(font="TkFixedFont")
        self.Entry1_2.configure(foreground="#000000")
        self.Entry1_2.configure(highlightbackground="#d9d9d9")
        self.Entry1_2.configure(highlightcolor="black")
        self.Entry1_2.configure(insertbackground="black")
        self.Entry1_2.configure(selectbackground="#c4c4c4")
        self.Entry1_2.configure(selectforeground="black")
        self.Entry1_2.configure(textvariable=n)
        self.Entry1_2.configure(state='disabled')

        self.Label2_13 = tk.Label(self.Canvas2)
        self.Label2_13.place(relx=0.506, rely=0.392, height=27, width=144)
        self.Label2_13.configure(activebackground="#f9f9f9")
        self.Label2_13.configure(activeforeground="black")
        self.Label2_13.configure(background="yellow")
        self.Label2_13.configure(disabledforeground="#a3a3a3")
        self.Label2_13.configure(font=font11)
        self.Label2_13.configure(foreground="black")
        self.Label2_13.configure(highlightbackground="#d9d9d9")
        self.Label2_13.configure(highlightcolor="black")
        self.Label2_13.configure(text='''Jumlah Uang''')

        self.Label2_14 = tk.Label(self.Canvas2)
        self.Label2_14.place(relx=0.510, rely=0.719, height=27, width=144)
        self.Label2_14.configure(activebackground="#f9f9f9")
        self.Label2_14.configure(activeforeground="black")
        self.Label2_14.configure(background="yellow")
        self.Label2_14.configure(disabledforeground="#a3a3a3")
        self.Label2_14.configure(font=font11)
        self.Label2_14.configure(foreground="black")
        self.Label2_14.configure(highlightbackground="#d9d9d9")
        self.Label2_14.configure(highlightcolor="black")
        self.Label2_14.configure(text='''Kembali Uang''')

        self.Entry1_7 = tk.Entry(self.Canvas2)
        self.Entry1_7.place(relx=0.772, rely=0.392,height=24, relwidth=0.178)
        self.Entry1_7.configure(background="white")
        self.Entry1_7.configure(disabledforeground="#a3a3a3")
        self.Entry1_7.configure(font="TkFixedFont")
        self.Entry1_7.configure(foreground="#000000")
        self.Entry1_7.configure(highlightbackground="#d9d9d9")
        self.Entry1_7.configure(highlightcolor="black")
        self.Entry1_7.configure(insertbackground="black")
        self.Entry1_7.configure(selectbackground="#c4c4c4")
        self.Entry1_7.configure(selectforeground="black")
        self.Entry1_7.configure(textvariable=o)

        self.Entry1_8 = tk.Entry(self.Canvas2)
        self.Entry1_8.place(relx=0.772, rely=0.719,height=24, relwidth=0.178)
        self.Entry1_8.configure(background="white")
        self.Entry1_8.configure(disabledforeground="#a3a3a3")
        self.Entry1_8.configure(font="TkFixedFont")
        self.Entry1_8.configure(foreground="#000000")
        self.Entry1_8.configure(highlightbackground="#d9d9d9")
        self.Entry1_8.configure(highlightcolor="black")
        self.Entry1_8.configure(insertbackground="black")
        self.Entry1_8.configure(selectbackground="#c4c4c4")
        self.Entry1_8.configure(selectforeground="black")
        self.Entry1_8.configure(textvariable=p)
        self.Entry1_8.configure(state='disabled')

        self.Label1_9 = tk.Label(self.Canvas2)
        self.Label1_9.place(relx=0.0, rely=0.0, height=36, width=592)
        self.Label1_9.configure(activebackground="#f9f9f9")
        self.Label1_9.configure(activeforeground="black")
        self.Label1_9.configure(anchor='w')
        self.Label1_9.configure(background="#ffffff")
        self.Label1_9.configure(disabledforeground="#a3a3a3")
        self.Label1_9.configure(font=font9)
        self.Label1_9.configure(foreground="black")
        self.Label1_9.configure(highlightbackground="#d9d9d9")
        self.Label1_9.configure(highlightcolor="white")
        self.Label1_9.configure(justify='left')
        self.Label1_9.configure(text='''Rincian Harga''')
        self.Label1_9.configure(width=592)

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.8, rely=0.416, height=33, width=106)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#0a0a51")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font11)
        self.Button1.configure(foreground="#ffffff")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''OK''',command=pricelist)
        self.Button1.configure(width=106)

        self.Button1_10 = tk.Button(top)
        self.Button1_10.place(relx=0.8, rely=0.897, height=33, width=106)
        self.Button1_10.configure(activebackground="#ececec")
        self.Button1_10.configure(activeforeground="#000000")
        self.Button1_10.configure(background="#0a0a51")
        self.Button1_10.configure(disabledforeground="#a3a3a3")
        self.Button1_10.configure(font=font11)
        self.Button1_10.configure(foreground="#ffffff")
        self.Button1_10.configure(highlightbackground="#d9d9d9")
        self.Button1_10.configure(highlightcolor="black")
        self.Button1_10.configure(pady="0")
        self.Button1_10.configure(text='''Selesai''',command=antar)
        self.Button1_10.configure(width=106)

        self.Button1_11 = tk.Button(top)
        self.Button1_11.place(relx=0.567, rely=0.897, height=33, width=106)
        self.Button1_11.configure(activebackground="#ececec")
        self.Button1_11.configure(activeforeground="#000000")
        self.Button1_11.configure(background="#0a0a51")
        self.Button1_11.configure(disabledforeground="#a3a3a3")
        self.Button1_11.configure(font=font11)
        self.Button1_11.configure(foreground="#ffffff")
        self.Button1_11.configure(highlightbackground="#d9d9d9")
        self.Button1_11.configure(highlightcolor="black")
        self.Button1_11.configure(pady="0")
        self.Button1_11.configure(text='''Total''',command=total)

        self.Button1_12 = tk.Button(top)
        self.Button1_12.place(relx=0.567, rely=0.416, height=33, width=106)
        self.Button1_12.configure(activebackground="#ececec")
        self.Button1_12.configure(activeforeground="#000000")
        self.Button1_12.configure(background="#0a0a51")
        self.Button1_12.configure(disabledforeground="#a3a3a3")
        self.Button1_12.configure(font=font11)
        self.Button1_12.configure(foreground="#ffffff")
        self.Button1_12.configure(highlightbackground="#d9d9d9")
        self.Button1_12.configure(highlightcolor="black")
        self.Button1_12.configure(pady="0")
        self.Button1_12.configure(text='''Ulangi''',command=ulangi)


if __name__ == '__main__':
    vp_start_gui()





