#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Dec 20, 2018 06:38:28 PM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import registered_support
import sqlite3
import time
from tkinter import messagebox

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    registered_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    registered_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font10 = "-family Arial -size 11 -weight normal -slant roman "  \
            "-underline 0 -overstrike 0"
        font11 = "-family Perpetua -size 20 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font12 = "-family {Segoe UI} -size 9 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"
        font9 = "-family Arial -size 10 -weight normal -slant roman "  \
            "-underline 0 -overstrike 0"

        top.geometry("606x500+525+253")
        top.title("Register Pelanggan")
        top.configure(background="#1b213d")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")
        self.Canvas1 = tk.Canvas(top)
        self.Canvas1.place(relx=0.017, rely=0.022, relheight=0.962
                , relwidth=0.962)
        self.Canvas1.configure(background="#57b754")
        self.Canvas1.configure(highlightbackground="#b6ce9b")
        self.Canvas1.configure(highlightcolor="#5b5b5b")
        self.Canvas1.configure(highlightthickness="0")
        self.Canvas1.configure(insertbackground="#5b5b5b")
        self.Canvas1.configure(relief='ridge')
        self.Canvas1.configure(selectbackground="#5b5b5b")
        self.Canvas1.configure(selectborderwidth="0")
        self.Canvas1.configure(selectforeground="#aaaaaa")
        self.Canvas1.configure(width=583)

        waktu = time.asctime(time.localtime(time.time()))
        jam = tk.Label(root,text=waktu,bg='#ffffff',font="Verdana 10")
        jam.place(x=400,y=20)

        nm=tk.StringVar()
        em=tk.StringVar()
        pw=tk.StringVar()
        jk=tk.StringVar()
        hp=tk.StringVar()
        al=tk.StringVar()

        def inserting():
            nma=nm.get()
            ema=em.get()
            pwd=pw.get()
            jkl=jk.get()
            n_hp=hp.get()
            ala=al.get()
            conn=sqlite3.connect("laundry.db")
            with conn :
                data = conn.cursor()
                data.execute("INSERT INTO member (nama_pelanggan,pass_word,email,no_hp,jenis_kelamin,alamat)"
                             "VALUES (?,?,?,?,?,?)",(nma,pwd,ema,n_hp,jkl,ala,))
                conn.commit()

        self.Label1 = tk.Label(self.Canvas1)
        self.Label1.place(relx=0.0, rely=0.0, height=44, width=585)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font11)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Daftar Member''')

        self.Label2 = tk.Label(self.Canvas1)
        self.Label2.place(relx=0.12, rely=0.185, height=25, width=48)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#57b754")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font9)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Nama''')

        self.Label2_6 = tk.Label(self.Canvas1)
        self.Label2_6.place(relx=0.12, rely=0.3, height=25, width=48)
        self.Label2_6.configure(activebackground="#f9f9f9")
        self.Label2_6.configure(activeforeground="black")
        self.Label2_6.configure(background="#57b754")
        self.Label2_6.configure(disabledforeground="#a3a3a3")
        self.Label2_6.configure(font=font9)
        self.Label2_6.configure(foreground="#000000")
        self.Label2_6.configure(highlightbackground="#d9d9d9")
        self.Label2_6.configure(highlightcolor="black")
        self.Label2_6.configure(text='''Email''')

        self.Label2_7 = tk.Label(self.Canvas1)
        self.Label2_7.place(relx=0.111, rely=0.762, height=26, width=62)
        self.Label2_7.configure(activebackground="#f9f9f9")
        self.Label2_7.configure(activeforeground="black")
        self.Label2_7.configure(background="#57b754")
        self.Label2_7.configure(disabledforeground="#a3a3a3")
        self.Label2_7.configure(font=font9)
        self.Label2_7.configure(foreground="#000000")
        self.Label2_7.configure(highlightbackground="#d9d9d9")
        self.Label2_7.configure(highlightcolor="black")
        self.Label2_7.configure(text='''Alamat''')

        self.Label2_8 = tk.Label(self.Canvas1)
        self.Label2_8.place(relx=0.12, rely=0.647, height=26, width=52)
        self.Label2_8.configure(activebackground="#f9f9f9")
        self.Label2_8.configure(activeforeground="black")
        self.Label2_8.configure(background="#57b754")
        self.Label2_8.configure(disabledforeground="#a3a3a3")
        self.Label2_8.configure(font=font9)
        self.Label2_8.configure(foreground="#000000")
        self.Label2_8.configure(highlightbackground="#d9d9d9")
        self.Label2_8.configure(highlightcolor="black")
        self.Label2_8.configure(text='''No HP''')

        self.Label2_9 = tk.Label(self.Canvas1)
        self.Label2_9.place(relx=0.103, rely=0.52, height=26, width=112)
        self.Label2_9.configure(activebackground="#f9f9f9")
        self.Label2_9.configure(activeforeground="black")
        self.Label2_9.configure(background="#57b754")
        self.Label2_9.configure(disabledforeground="#a3a3a3")
        self.Label2_9.configure(font=font9)
        self.Label2_9.configure(foreground="#000000")
        self.Label2_9.configure(highlightbackground="#d9d9d9")
        self.Label2_9.configure(highlightcolor="black")
        self.Label2_9.configure(text='''Jenis Kelamin''')

        self.Label2_10 = tk.Label(self.Canvas1)
        self.Label2_10.place(relx=0.103, rely=0.404, height=26, width=92)
        self.Label2_10.configure(activebackground="#f9f9f9")
        self.Label2_10.configure(activeforeground="black")
        self.Label2_10.configure(background="#57b754")
        self.Label2_10.configure(disabledforeground="#a3a3a3")
        self.Label2_10.configure(font=font9)
        self.Label2_10.configure(foreground="#000000")
        self.Label2_10.configure(highlightbackground="#d9d9d9")
        self.Label2_10.configure(highlightcolor="black")
        self.Label2_10.configure(text='''Password''')

        self.Entry1 = tk.Entry(self.Canvas1)
        self.Entry1.place(relx=0.515, rely=0.185,height=24, relwidth=0.367)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")
        self.Entry1.configure(textvar=nm)

        self.Entry1_12 = tk.Entry(self.Canvas1)
        self.Entry1_12.place(relx=0.515, rely=0.416,height=24, relwidth=0.367)
        self.Entry1_12.configure(background="white")
        self.Entry1_12.configure(disabledforeground="#a3a3a3")
        self.Entry1_12.configure(font="TkFixedFont")
        self.Entry1_12.configure(foreground="#000000")
        self.Entry1_12.configure(highlightbackground="#d9d9d9")
        self.Entry1_12.configure(highlightcolor="black")
        self.Entry1_12.configure(insertbackground="black")
        self.Entry1_12.configure(selectbackground="#c4c4c4")
        self.Entry1_12.configure(selectforeground="black")
        self.Entry1_12.configure(textvar=pw,show='*')

        self.Entry1_13 = tk.Entry(self.Canvas1)
        self.Entry1_13.place(relx=0.515, rely=0.3,height=24, relwidth=0.367)
        self.Entry1_13.configure(background="white")
        self.Entry1_13.configure(disabledforeground="#a3a3a3")
        self.Entry1_13.configure(font="TkFixedFont")
        self.Entry1_13.configure(foreground="#000000")
        self.Entry1_13.configure(highlightbackground="#d9d9d9")
        self.Entry1_13.configure(highlightcolor="black")
        self.Entry1_13.configure(insertbackground="black")
        self.Entry1_13.configure(selectbackground="#c4c4c4")
        self.Entry1_13.configure(selectforeground="black")
        self.Entry1_13.configure(textvar=em)

        self.Entry1_14 = tk.Entry(self.Canvas1)
        self.Entry1_14.place(relx=0.515, rely=0.762,height=24, relwidth=0.367)
        self.Entry1_14.configure(background="white")
        self.Entry1_14.configure(disabledforeground="#a3a3a3")
        self.Entry1_14.configure(font="TkFixedFont")
        self.Entry1_14.configure(foreground="#000000")
        self.Entry1_14.configure(highlightbackground="#d9d9d9")
        self.Entry1_14.configure(highlightcolor="black")
        self.Entry1_14.configure(insertbackground="black")
        self.Entry1_14.configure(selectbackground="#c4c4c4")
        self.Entry1_14.configure(selectforeground="black")
        self.Entry1_14.configure(textvar=al)

        self.Entry1_15 = tk.Entry(self.Canvas1)
        self.Entry1_15.place(relx=0.515, rely=0.647,height=24, relwidth=0.367)
        self.Entry1_15.configure(background="white")
        self.Entry1_15.configure(disabledforeground="#a3a3a3")
        self.Entry1_15.configure(font="TkFixedFont")
        self.Entry1_15.configure(foreground="#000000")
        self.Entry1_15.configure(highlightbackground="#d9d9d9")
        self.Entry1_15.configure(highlightcolor="black")
        self.Entry1_15.configure(insertbackground="black")
        self.Entry1_15.configure(selectbackground="#c4c4c4")
        self.Entry1_15.configure(selectforeground="black")
        self.Entry1_15.configure(textvar=hp)

        def move4():
            inserting()
            messagebox.showinfo("OK!!","Registrasi Berhasil")
            root.destroy()
            from orderan import vp_start_gui
            vp_start_gui()

        self.Button1 = tk.Button(self.Canvas1)
        self.Button1.place(relx=0.772, rely=0.878, height=33, width=106)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#ffffff")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font12)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''DAFTAR''',command=move4)
        self.Radiobutton1 = tk.Radiobutton(self.Canvas1)
        self.Radiobutton1.place(relx=0.617, rely=0.531, relheight=0.065
                , relwidth=0.063)
        self.Radiobutton1.configure(activebackground="#ececec")
        self.Radiobutton1.configure(activeforeground="#000000")
        self.Radiobutton1.configure(background="#57b754")
        self.Radiobutton1.configure(borderwidth="0")
        self.Radiobutton1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1.configure(font=font10)
        self.Radiobutton1.configure(foreground="#000000")
        self.Radiobutton1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1.configure(highlightcolor="#f4f4f4")
        self.Radiobutton1.configure(justify='left')
        self.Radiobutton1.configure(text='''L''',variable=jk,value="L")


        self.Radiobutton1_1 = tk.Radiobutton(self.Canvas1)
        self.Radiobutton1_1.place(relx=0.72, rely=0.531, relheight=0.065
                , relwidth=0.063)
        self.Radiobutton1_1.configure(activebackground="#ececec")
        self.Radiobutton1_1.configure(activeforeground="#000000")
        self.Radiobutton1_1.configure(background="#57b754")
        self.Radiobutton1_1.configure(borderwidth="0")
        self.Radiobutton1_1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1_1.configure(font=font10)
        self.Radiobutton1_1.configure(foreground="#000000")
        self.Radiobutton1_1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1_1.configure(highlightcolor="#f4f4f4")
        self.Radiobutton1_1.configure(justify='left')
        self.Radiobutton1_1.configure(text='''P''',variable=jk,value="P")

if __name__ == '__main__':
    vp_start_gui()





